[project]
name = "davidkhala.ml.ocr"
version = "0.0.4"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pydantic", "davidkhala-utils"]

[project.optional-dependencies]
paddle = ["paddleocr", "paddlepaddle==3.2.*"]
paddle-ocr = ["paddlenlp==3.0.0b4; python_version < '3.12'", "pip", "setuptools", "aistudio-sdk==0.2.6"]
docling = ["docling"]

[tool.hatch.build.targets.sdist]
include = ["davidkhala"]

[tool.hatch.build.targets.wheel]
include = ["davidkhala"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest"
]
docling-vlm = [
    "docling[vlm]",
    "hf_xet",
]
docling-text = [
    "rapidocr<3.9" # known issue https://github.com/docling-project/docling/issues/3694
]


[tool.uv]
prerelease = "allow"