name: nlp
on:
  push:
jobs:
  presidio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          extras: presidio
          working-directory: nlp/py
          groups: presidio-image presidio-text
      - name: prepare spaCy
        working-directory: nlp/py
        run: |
          uv pip install pip
          uv run spacy download en_core_web_lg
      - uses: davidkhala/setup-tesseract@main
      - name: test
        run: uv run pytest
        working-directory: nlp/py/tests
